# Generated by Django 3.2.2 on 2022-02-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proctor', '0007_auto_20220220_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
